/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Timer;

import javax.swing.JOptionPane;

import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Joctan Esquivel
 */
public class InterfazCalcu extends javax.swing.JFrame {
    
    public boolean isBinary = false;

    /**
     * Creates new form InterfazCalcu
     */
    public InterfazCalcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfPantalla = new javax.swing.JTextField();
        btnBinario = new javax.swing.JButton();
        btnPrimo = new javax.swing.JButton();
        btnData = new javax.swing.JButton();
        btnNumero1 = new javax.swing.JButton();
        btnNumero2 = new javax.swing.JButton();
        btnNumero3 = new javax.swing.JButton();
        btnNumero5 = new javax.swing.JButton();
        btnNumero6 = new javax.swing.JButton();
        btnNumero4 = new javax.swing.JButton();
        btnNumero9 = new javax.swing.JButton();
        btnNumero7 = new javax.swing.JButton();
        btnNumero8 = new javax.swing.JButton();
        btnNumero0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnAvg = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnBlancoNegro = new javax.swing.JToggleButton();
        btnC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La calculadora mas pichuda FUCK JAVIER");
        setBackground(new java.awt.Color(238, 248, 255));

        txfPantalla.setBackground(new java.awt.Color(255, 255, 255));
        txfPantalla.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        txfPantalla.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPantallaActionPerformed(evt);
            }
        });
        txfPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfPantallaKeyReleased(evt);
            }
        });

        btnBinario.setBackground(new java.awt.Color(197, 233, 255));
        btnBinario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBinario.setText("Binario");
        btnBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarioActionPerformed(evt);
            }
        });

        btnPrimo.setBackground(new java.awt.Color(197, 233, 255));
        btnPrimo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPrimo.setText("Primo");
        btnPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimoActionPerformed(evt);
            }
        });

        btnData.setBackground(new java.awt.Color(197, 233, 255));
        btnData.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnData.setText("Data");

        btnNumero1.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero1.setText("1");
        btnNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero1ActionPerformed(evt);
            }
        });

        btnNumero2.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero2.setText("2");
        btnNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero2ActionPerformed(evt);
            }
        });

        btnNumero3.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero3.setText("3");
        btnNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero3ActionPerformed(evt);
            }
        });

        btnNumero5.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero5.setText("5");
        btnNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero5ActionPerformed(evt);
            }
        });

        btnNumero6.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero6.setText("6");
        btnNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero6ActionPerformed(evt);
            }
        });

        btnNumero4.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero4.setText("4");
        btnNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero4ActionPerformed(evt);
            }
        });

        btnNumero9.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero9.setText("9");
        btnNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero9ActionPerformed(evt);
            }
        });

        btnNumero7.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero7.setText("7");
        btnNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero7ActionPerformed(evt);
            }
        });

        btnNumero8.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero8.setText("8");
        btnNumero8.setToolTipText("");
        btnNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero8ActionPerformed(evt);
            }
        });

        btnNumero0.setBackground(new java.awt.Color(197, 233, 255));
        btnNumero0.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnNumero0.setText("0");
        btnNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero0ActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(197, 233, 255));
        btnPunto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(197, 233, 255));
        btnDivision.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnResta.setBackground(new java.awt.Color(197, 233, 255));
        btnResta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnSuma.setBackground(new java.awt.Color(197, 233, 255));
        btnSuma.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnMultiplicacion.setBackground(new java.awt.Color(197, 233, 255));
        btnMultiplicacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnMultiplicacion.setText("*");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnAvg.setBackground(new java.awt.Color(197, 233, 255));
        btnAvg.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnAvg.setText("Avg");

        btnIgual.setBackground(new java.awt.Color(105, 155, 186));
        btnIgual.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnM.setBackground(new java.awt.Color(197, 233, 255));
        btnM.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnM.setText("M+");

        btnBlancoNegro.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        btnBlancoNegro.setForeground(new java.awt.Color(51, 51, 51));
        btnBlancoNegro.setText("☾");
        btnBlancoNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlancoNegroActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(197, 233, 255));
        btnC.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfPantalla, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnBlancoNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAvg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txfPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBlancoNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(btnPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPantallaActionPerformed
        // TODO add your handling code here:
        eventosDelTeclado();
 
        
    }//GEN-LAST:event_txfPantallaActionPerformed

    private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimoActionPerformed

    
    
    private void btnBlancoNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlancoNegroActionPerformed
        // TODO add your handling code here:
        if (this.btnBlancoNegro.isSelected()){
            getContentPane().setBackground(new Color(53,53,53));
            this.btnBlancoNegro.setText("☀");
            this.btnAvg.setBackground(new Color(147,147,147));
            this.btnBinario.setBackground(new Color(147,147,147));
            this.btnC.setBackground(new Color(147,147,147));
            this.btnData.setBackground(new Color(147,147,147));
            this.btnDivision.setBackground(new Color(147,147,147));
            this.btnIgual.setBackground(new Color( 245, 245, 245 ));
            this.btnM.setBackground(new Color(147,147,147));
            this.btnMultiplicacion.setBackground(new Color(147,147,147));
            this.btnNumero0.setBackground(new Color(147,147,147));
            this.btnNumero1.setBackground(new Color(147,147,147));
            this.btnNumero2.setBackground(new Color(147,147,147));
            this.btnNumero3.setBackground(new Color(147,147,147));
            this.btnNumero4.setBackground(new Color(147,147,147));
            this.btnNumero5.setBackground(new Color(147,147,147));
            this.btnNumero6.setBackground(new Color(147,147,147));
            this.btnNumero7.setBackground(new Color(147,147,147));
            this.btnNumero8.setBackground(new Color(147,147,147));
            this.btnNumero9.setBackground(new Color(147,147,147));
            this.btnNumero0.setBackground(new Color(147,147,147));
            this.btnPrimo.setBackground(new Color(147,147,147));
            this.btnPunto.setBackground(new Color(147,147,147));
            this.btnResta.setBackground(new Color(147,147,147));
            this.btnSuma.setBackground(new Color(147,147,147));
            
            
           
        }else{
            getContentPane().setBackground(new Color( 238, 248, 255 ));
            this.btnBlancoNegro.setText("☾");
            this.btnAvg.setBackground(new Color(197,233,255));
            this.btnBinario.setBackground(new Color(197,233,255));
            this.btnC.setBackground(new Color(197,233,255));
            this.btnData.setBackground(new Color(197,233,255));
            this.btnDivision.setBackground(new Color(197,233,255));
            this.btnIgual.setBackground(new Color( 117, 178, 214 ));
            this.btnM.setBackground(new Color(197,233,255));
            this.btnMultiplicacion.setBackground(new Color(197,233,255));
            this.btnNumero0.setBackground(new Color(197,233,255));
            this.btnNumero1.setBackground(new Color(197,233,255));
            this.btnNumero2.setBackground(new Color(197,233,255));
            this.btnNumero3.setBackground(new Color(197,233,255));
            this.btnNumero4.setBackground(new Color(197,233,255));
            this.btnNumero5.setBackground(new Color(197,233,255));
            this.btnNumero6.setBackground(new Color(197,233,255));
            this.btnNumero7.setBackground(new Color(197,233,255));
            this.btnNumero8.setBackground(new Color(197,233,255));
            this.btnNumero9.setBackground(new Color(197,233,255));
            this.btnNumero0.setBackground(new Color(197,233,255));
            this.btnPrimo.setBackground(new Color(197,233,255));
            this.btnPunto.setBackground(new Color(197,233,255));
            this.btnResta.setBackground(new Color(197,233,255));
            this.btnSuma.setBackground(new Color(197,233,255));
            
        }
    }//GEN-LAST:event_btnBlancoNegroActionPerformed

    private void btnNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero1ActionPerformed
        // TODO add your handling code here:
        if (isBinary){
            this.txfPantalla.setText("1");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"1");
        }
        
    }//GEN-LAST:event_btnNumero1ActionPerformed

    private void btnNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero2ActionPerformed
        // TODO add your handling code here:
        if (isBinary){
            this.txfPantalla.setText("2");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"2");
        }
    }//GEN-LAST:event_btnNumero2ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        this.txfPantalla.setText("");
        this.isBinary=false;
    }//GEN-LAST:event_btnCActionPerformed

    private void btnNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero3ActionPerformed
        // TODO add your handling code here:
         if (isBinary){
            this.txfPantalla.setText("3");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"3");
         }
    }//GEN-LAST:event_btnNumero3ActionPerformed

    private void btnNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero4ActionPerformed
        // TODO add your handling code here:
         if (isBinary){
            this.txfPantalla.setText("4");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"4");
         }
    }//GEN-LAST:event_btnNumero4ActionPerformed

    private void btnNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero5ActionPerformed
        // TODO add your handling code here:
         if (isBinary){
            this.txfPantalla.setText("5");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"5");
         }
    }//GEN-LAST:event_btnNumero5ActionPerformed

    private void btnNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero6ActionPerformed
        // TODO add your handling code here:
         if (isBinary){
            this.txfPantalla.setText("6");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"6");
         }
    }//GEN-LAST:event_btnNumero6ActionPerformed

    private void btnNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero7ActionPerformed
        // TODO add your handling code here:
        if (isBinary){
            this.txfPantalla.setText("7");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"7");
         }
    }//GEN-LAST:event_btnNumero7ActionPerformed

    private void btnNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero8ActionPerformed
        // TODO add your handling code here:
       if (isBinary){
            this.txfPantalla.setText("8");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"8");
         }
    }//GEN-LAST:event_btnNumero8ActionPerformed

    private void btnNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero9ActionPerformed
        // TODO add your handling code here:
        if (isBinary){
            this.txfPantalla.setText("9");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"9");
         }
    }//GEN-LAST:event_btnNumero9ActionPerformed

    private void btnNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero0ActionPerformed
        // TODO add your handling code here:
        if (isBinary){
            this.txfPantalla.setText("0");
            this.isBinary=false;
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+"0");
         }
    }//GEN-LAST:event_btnNumero0ActionPerformed

    
    public int countChar(String str, char c){
    int count = 0;

    for(int i=0; i < str.length(); i++)
    {    if(str.charAt(i) == c)
            count++;
    }

    return count;
}

    boolean isPoint(String screen){
        Operaciones pantalla = new Operaciones(this.txfPantalla.getText());
        String result1;
        String result2 = "";
        String  character;
        try{
            
            
            for (int i =0; i<screen.length();i++){
                 character = screen.substring(i, i+1);
                 if (character.equals("/") | character.equals("*") |
                      character.equals("+") | character.equals("-") ){
                     if (i==0){
                         continue;
                     }
                      result1 = screen.substring(i+1);
                      if(countChar(result1, '.')!=1){
                          return false;
                    
                 }
            }
            }
            
        boolean numeroNegativo = false;
        
       
        
        character="";
        for (int i =0; i<screen.length();i++){
             character = screen.substring(i, i+1);
             if (character.equals("/") | character.equals("*") |
                  character.equals("+") | character.equals("-") ){
                 if (i==0){
                     numeroNegativo=true;
                     continue;
                 }
                 
                  
             }else{
                 result2+=character;
                 if(countChar(result2, '.')!=1){
                          return false;
             }
             
         }
        }
        return true;
           
    }catch(Exception e){
        boolean numeroNegativo = false;
        
       
        
        character="";
        for (int i =0; i<screen.length();i++){
             character = screen.substring(i, i+1);
             if (character.equals("/") | character.equals("*") |
                  character.equals("+") | character.equals("-") ){
                 if (i==0){
                     numeroNegativo=true;
                     continue;
                 }
                 
                  
             }else{
                 result2+=character;
                 if(countChar(result2, '.')!=1){
                          return false;
             }
             
         }
        }
        return true;
    }
        
    }
    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        if (this.isPoint(this.txfPantalla.getText()))
            JOptionPane.showMessageDialog(this, "Ya existe un punto", "Error", JOptionPane.ERROR_MESSAGE);
        else if(this.txfPantalla.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se puede poner un punto si no hay números", "Error", JOptionPane.ERROR_MESSAGE);
            
        }else{
            this.txfPantalla.setText(this.txfPantalla.getText()+".");
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        Operaciones resultado = new Operaciones(this.txfPantalla.getText());
        
        String screen = this.txfPantalla.getText();
        
        
        
        
        if (this.txfPantalla.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe existir un numero primero", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (this.isBinary==false){
            
            if (resultado.existenDosNumero(resultado.getNum1(screen), resultado.getNum2(screen), resultado.getSigno(screen))){
                this.txfPantalla.setText(resultado.getResultado()+"/");
                }else {
                this.txfPantalla.setText(this.txfPantalla.getText()+"/");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede tranajar con binarios", "Error", JOptionPane.ERROR_MESSAGE);
            this.isBinary=false;
            this.txfPantalla.setText("");
        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        // TODO add your handling code here:
         Operaciones resultado = new Operaciones(this.txfPantalla.getText());
        
        String screen = this.txfPantalla.getText();
        
        
        
        
        if (this.txfPantalla.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe existir un numero primero", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (this.isBinary==false){
            
            if (resultado.existenDosNumero(resultado.getNum1(screen), resultado.getNum2(screen), resultado.getSigno(screen))){
                this.txfPantalla.setText(resultado.getResultado()+"*");
                }else {
                this.txfPantalla.setText(this.txfPantalla.getText()+"*");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede tranajar con binarios", "Error", JOptionPane.ERROR_MESSAGE);
            this.isBinary=false;
            this.txfPantalla.setText("");
        }
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        Operaciones resultado = new Operaciones(this.txfPantalla.getText());
        
        String screen = this.txfPantalla.getText();
        
        
           
        
       
            if (this.isBinary==false){
            
            if (screen.equals("")){
                this.txfPantalla.setText("-");
            }else if (screen.equals("-")){
                this.txfPantalla.setText("");
                
                //checkear esta parte del codigo, no quiere funcar el cambio de - - a +
            }else if(resultado.getSigno(screen)==2){
                
                System.out.println("FUCK");
                int end = screen.length()-1;
                this.txfPantalla.setText(screen.substring(0,end )+"+");
            } else if (resultado.existenDosNumero(resultado.getNum1(screen), resultado.getNum2(screen), resultado.getSigno(screen))){
                System.out.println("FUCK  fbbff");
                this.txfPantalla.setText(resultado.getResultado()+"-");
                }else {
                this.txfPantalla.setText(this.txfPantalla.getText()+"-");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede tranajar con binarios", "Error", JOptionPane.ERROR_MESSAGE);
            this.isBinary=false;
            this.txfPantalla.setText("");
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        Operaciones resultado = new Operaciones(this.txfPantalla.getText());
        
        String screen = this.txfPantalla.getText();
        
        
        
        
        if (this.txfPantalla.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe existir un numero primero", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (this.isBinary==false){
            
            if (resultado.existenDosNumero(resultado.getNum1(screen), resultado.getNum2(screen), resultado.getSigno(screen))){
                this.txfPantalla.setText(resultado.getResultado()+"+");
                }else {
                this.txfPantalla.setText(this.txfPantalla.getText()+"+");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se puede tranajar con binarios", "Error", JOptionPane.ERROR_MESSAGE);
            this.isBinary=false;
            this.txfPantalla.setText("");
        }
        
        
       
    }//GEN-LAST:event_btnSumaActionPerformed

    public void eventosDelTeclado(){
        
        KeyListener l = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
             }

            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyChar()=='a'){
                    System.out.println("A");
                }
            }
        };
        this.txfPantalla.addKeyListener(l);
       
        
        
    }
    
    
    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        Operaciones resultado = new Operaciones(this.txfPantalla.getText());
        this.txfPantalla.setText(resultado.getResultado()+"");
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarioActionPerformed
        // TODO add your handling code here:
        Operaciones numero = new Operaciones(this.txfPantalla.getText());
        if (numero.existeUnNumero(numero.getNum1(this.txfPantalla.getText()),
                numero.getNum2(this.txfPantalla.getText()) , numero.getSigno(this.txfPantalla.getText()))){
            this.txfPantalla.setText(numero.toBinary(this.txfPantalla.getText()));
            this.isBinary=true;
        
    }else if(numero.existenDosNumero(numero.getNum1(this.txfPantalla.getText()), numero.getNum2(this.txfPantalla.getText()),numero.getSigno(this.txfPantalla.getText()))){
            
            this.txfPantalla.setText(numero.getResultado()+"");
            

            this.txfPantalla.setText(numero.toBinary(this.txfPantalla.getText()));
            this.isBinary=true;
            
            
            
            
        }
        
       
        
        
    }//GEN-LAST:event_btnBinarioActionPerformed

    private void txfPantallaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPantallaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar()=='a'){
            
            
            Timer delay = new Timer();
            
            
            this.btnNumero0.setBackground(new Color(150,200,220));
                
           
            
        }
    }//GEN-LAST:event_txfPantallaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCalcu().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvg;
    private javax.swing.JButton btnBinario;
    private javax.swing.JToggleButton btnBlancoNegro;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNumero0;
    private javax.swing.JButton btnNumero1;
    private javax.swing.JButton btnNumero2;
    private javax.swing.JButton btnNumero3;
    private javax.swing.JButton btnNumero4;
    private javax.swing.JButton btnNumero5;
    private javax.swing.JButton btnNumero6;
    private javax.swing.JButton btnNumero7;
    private javax.swing.JButton btnNumero8;
    private javax.swing.JButton btnNumero9;
    private javax.swing.JButton btnPrimo;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JTextField txfPantalla;
    // End of variables declaration//GEN-END:variables
}
